### ISSUE TITLE
RUns on H1C IDR2.2 data (issue summary)

### ISSUE THREAD

**Issue by philbull** [HydraRadio/hydra-pspec#73]
This issue just summarises problems with running hydra-pspec on real data as they come up.

**Comment by philbull** [comment]
Even though --clobber is set, it doesn't like the existing JSON file.
```(hera) [dc-bull2@login8b ~]$ tail idr22_hydra_pspec.sh.e7325346 
Traceback (most recent call last):
  File "/cosma/home/dp270/dc-bull2/software/hydra-pspec/run-hydra-pspec.py", line 357, in <module>
    parser.save(args, out_dir / "args.json", format="json_indented", skip_none=False)
  File "/cosma/home/dp270/dc-bull2/.conda/envs/hera/lib/python3.9/site-packages/jsonargparse/_deprecated.py", line 159, in patched_save
    return self._unpatched_save(cfg, *args, multifile=multifile, **kwargs)
  File "/cosma/home/dp270/dc-bull2/.conda/envs/hera/lib/python3.9/site-packages/jsonargparse/_core.py", line 836, in save
    check_overwrite(path_fc)
  File "/cosma/home/dp270/dc-bull2/.conda/envs/hera/lib/python3.9/site-packages/jsonargparse/_core.py", line 817, in check_overwrite
    raise ValueError(f"Refusing to overwrite existing file: {path.absolute}")
ValueError: Refusing to overwrite existing file: /cosma8/data/dp270/dc-bull2/hera/IDR2_2/hydra_pspec/results-seed-7123689-Niter-1000/args.json```

**Comment by philbull** [comment]
Running using command-line arguments doesn't work unless a config file is also specified. So may as well just use the config file.
